import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { MotionValue } from 'framer-motion';
import { useUserStore } from '../../store/userStore';

// Global Cache for persistent frame images across unmounts/renders
const GLOBAL_FRAME_CACHE: Record<string, HTMLImageElement[]> = {};

const DISCLAIMER_TEXT = `About The Game
At Your Age (AYA) is an interactive personality discovery game designed for entertainment and personal reflection purposes only. The scenarios, stories and personality assessments presented in this app are fictional simulations inspired by publicly available historical information and are not intended to be factually comprehensive or academically verified.

About Personality Assessments
The personality profiles, DNA reports, trait scores, Future Self predictions and archetype matches generated by AYA are based on in-game decisions and quiz responses. They are designed for entertainment and self-reflection only. They do not constitute professional psychological assessments, career advice, mental health evaluations or any form of clinical diagnosis. Results should not be used as the basis for any major life decisions.

About Real People
AYA features fictional game scenarios inspired by the lives of real public figures. These scenarios are creative interpretations and simulations — they do not claim to accurately represent the actual thoughts, decisions, beliefs or private lives of any individual. All dialogue and choices presented are fictional. Resemblance to actual events is used for inspirational and educational purposes only.

About User Data
AYA collects basic user information including name, age and mobile number to personalize your experience. We collect behavioral data including quiz responses, in-game choices and session data to improve our recommendations. We do not sell individual personal data to third parties. Aggregated and anonymized insights may be used for research and product improvement. By using AYA you consent to the collection and use of this data as described in our Privacy Policy.

About Push Notifications
If you enable push notifications AYA may send you daily reminders and motivational messages. You can disable notifications at any time through your device settings.

Age Requirement
AYA is designed for users aged 13 and above. Users under 18 should use this app with parental awareness. We do not knowingly collect personal information from children under 13.

Mental Health Notice
Some story scenarios may touch on themes including failure, rejection, loss, loneliness and emotional struggle. These are presented in an educational and motivational context. If you are experiencing mental health difficulties please seek support from a qualified professional.

No Guarantees
AYA makes no guarantees about the accuracy of personality assessments, future self predictions or archetype matches. These features are designed to inspire reflection and curiosity — not to predict your actual future.

Contact
For questions or concerns about this disclaimer or your data please contact us at: atyourage@gmail.com
Last updated: April 2026`;

interface AntiGravityCanvasProps {
    progress: MotionValue<number>;
    onReady: () => void;
}

export function AntiGravityCanvas({ progress, onReady }: AntiGravityCanvasProps) {
    const isCandyMode = useUserStore((state) => state.isCandyMode);
    const totalFrames = isCandyMode ? 40 : 240;
    const folder = isCandyMode ? 'map_frames' : 'map_frames_dark';

    const canvasRef = useRef<HTMLCanvasElement>(null);
    const imagesRef = useRef<HTMLImageElement[]>(GLOBAL_FRAME_CACHE[folder] || []);
    const [imagesLoaded, setImagesLoaded] = useState(0);
    const [isReady, setIsReady] = useState(false);
    const [isImagesLoaded, setIsImagesLoaded] = useState(false);
    const [isVideoFinished, setIsVideoFinished] = useState(false);
    
    const videoRef = useRef<HTMLVideoElement>(null);
    const [showPlayButton, setShowPlayButton] = useState(false);
    const [isVideoPlaying, setIsVideoPlaying] = useState(false);
    const [isFadingOut, setIsFadingOut] = useState(false);

    // References for the vanilla animation loop to avoid React renders
    const loopRef = useRef<number>(0);
    const lastProgressRef = useRef<number>(-1);

    // Preload Images
    useEffect(() => {
        // If we already have the requested frames fully cached, set instantly and return!
        if (GLOBAL_FRAME_CACHE[folder] && GLOBAL_FRAME_CACHE[folder].length === totalFrames) {
            imagesRef.current = GLOBAL_FRAME_CACHE[folder];
            lastProgressRef.current = -1; // CRITICAL: Force the `tick` loop to redraw using the new cache
            setIsImagesLoaded(true);
            return;
        }

        // Only show loading if we have absolute NO cached frames playing in the engine
        if (imagesRef.current.length === 0) {
            setIsImagesLoaded(false);
            setImagesLoaded(0);
        }

        let loadedCount = 0;
        const loadedImages: HTMLImageElement[] = new Array(totalFrames);
        let mounted = true;

        for (let i = 1; i <= totalFrames; i++) {
            const img = new Image();
            img.src = `/assets/${folder}/ezgif-frame-${i.toString().padStart(3, '0')}.jpg`;
            img.onload = () => {
                if (!mounted) return;
                loadedCount++;

                // Track loading progress only if we are displaying the loading screen
                if (!isImagesLoaded) {
                    setImagesLoaded(loadedCount);
                }

                if (loadedCount === totalFrames) {
                    GLOBAL_FRAME_CACHE[folder] = loadedImages;     // Cache globally
                    imagesRef.current = loadedImages;              // Overwrite current holds safely
                    lastProgressRef.current = -1;                  // CRITICAL: Force the `tick` loop to instantly paint the new theme
                    setIsImagesLoaded(true);
                }
            };
            loadedImages[i - 1] = img;
        }

        return () => {
            mounted = false;
        };
        // Removed `onReady` and `isCandyMode` from deps, dependent uniquely on `folder` logic.
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [folder, totalFrames]);

    // Effect to handle total readiness
    useEffect(() => {
        if (isImagesLoaded && isVideoFinished) {
            setIsReady(true);
            onReady();
        }
    }, [isImagesLoaded, isVideoFinished, onReady]);

    // Handle video auto-play and mute policy
    useEffect(() => {
        if (!isReady && videoRef.current) {
            // Give it a tiny delay to ensure the DOM is ready for media playback
            const timer = setTimeout(() => {
                if (videoRef.current) {
                    videoRef.current.play().catch(err => {
                        // If browser blocks unmuted autoplay, show the play button overlay
                        if (err.name === 'NotAllowedError' || err.name === 'NotSupportedError') {
                            setShowPlayButton(true);
                        }
                    });
                }
            }, 100);
            return () => clearTimeout(timer);
        }
    }, [isReady]);

    const handleManualPlay = () => {
        if (videoRef.current) {
            videoRef.current.play().then(() => {
                setShowPlayButton(false);
            }).catch(console.error);
        }
    };

    // High Performance Engine Loop
    useEffect(() => {
        if (!isReady || !canvasRef.current || !imagesRef.current.length) return;

        const canvas = canvasRef.current;
        const ctx = canvas.getContext('2d', { alpha: false }); // Disable alpha for max perf
        if (!ctx) return;

        let canvasWidth = window.innerWidth;
        let canvasHeight = window.innerHeight;
        let dpr = window.devicePixelRatio || 1;

        // Configuration setup
        const setupCanvasContext = () => {
            canvasWidth = window.innerWidth;
            canvasHeight = window.innerHeight;
            dpr = window.devicePixelRatio || 1;

            canvas.width = canvasWidth * dpr;
            canvas.height = canvasHeight * dpr;
            canvas.style.width = `${canvasWidth}px`;
            canvas.style.height = `${canvasHeight}px`;

            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
        };

        setupCanvasContext();

        // Optimized native draw function (no React lifecycle tied)
        const renderNativeFrame = (val: number) => {
            const index = Math.floor(val * (totalFrames - 1));
            const safeIndex = Math.max(0, Math.min(totalFrames - 1, index));
            const img = imagesRef.current[safeIndex];

            if (!img) return;

            // Direct calculate avoiding state
            const canvasRatio = (canvasWidth * dpr) / (canvasHeight * dpr);
            const imgRatio = img.width / img.height;

            let drawWidth = canvasWidth * dpr;
            let drawHeight = canvasHeight * dpr;
            let offsetX = 0;
            let offsetY = 0;

            if (canvasRatio > imgRatio) {
                drawHeight = (canvasWidth * dpr) / imgRatio;
                offsetY = ((canvasHeight * dpr) - drawHeight) / 2;
            } else {
                drawWidth = (canvasHeight * dpr) * imgRatio;
                offsetX = ((canvasWidth * dpr) - drawWidth) / 2;
            }

            ctx.drawImage(img, offsetX, offsetY, drawWidth, drawHeight);
        };

        // Window Resize
        const handleResize = () => {
            setupCanvasContext();
            lastProgressRef.current = -1; // Force a redraw
            renderNativeFrame(progress.get() || 0); // Force immediate redraw on resize
        };
        window.addEventListener('resize', handleResize);

        // Vanilla JS Render Loop - Runs continuously, independent of React
        const tick = () => {
            const currentProgress = progress.get() || 0; // fallback to 0 if undefined/NaN

            // Only draw if scroll progress actually changed
            if (currentProgress !== lastProgressRef.current) {
                renderNativeFrame(currentProgress);
                lastProgressRef.current = currentProgress;
            }

            loopRef.current = requestAnimationFrame(tick);
        };

        // FORCE FIRST PAINT IMMEDIATELY (Don't wait for scroll delta or tick loop to catch up)
        renderNativeFrame(progress.get() || 0);

        // Start Loop
        tick();

        return () => {
            window.removeEventListener('resize', handleResize);
            cancelAnimationFrame(loopRef.current);
        };
    }, [isReady, progress, totalFrames]); // Only rebinds if completely Unready/Ready again

    return (
        <>
            {!isReady && createPortal(
                <div className="fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-[#050814]">
                    <div 
                        onClick={showPlayButton ? handleManualPlay : undefined}
                        className={`absolute inset-0 z-20 flex flex-col p-6 sm:p-10 bg-[#050814] text-slate-400 font-mono text-[10px] sm:text-xs overflow-y-auto leading-relaxed whitespace-pre-wrap transition-opacity duration-1000 ease-in-out ${(!isVideoPlaying && !isVideoFinished) ? 'opacity-100' : 'opacity-0 pointer-events-none'} ${showPlayButton ? 'cursor-pointer' : ''}`}
                    >
                        <h2 className="text-[#00f1fe] text-lg sm:text-xl font-bold mb-4 uppercase tracking-widest border-b border-[#00f1fe]/30 pb-2">AYA — Legal Disclaimer</h2>
                        <div className="opacity-80">
                            {DISCLAIMER_TEXT}
                        </div>
                        
                        {showPlayButton && (
                            <div className="mt-8 mb-12 text-center text-[#00f1fe] font-black tracking-[0.2em] animate-pulse text-xs sm:text-sm border border-[#00f1fe]/30 py-4 rounded-lg bg-[#00f1fe]/5 shadow-[0_0_15px_rgba(0,241,254,0.1)]">
                                TAP ANYWHERE TO AGREE & START
                            </div>
                        )}
                    </div>

                    <video
                        ref={videoRef}
                        src="/assets/intro.mp4"
                        autoPlay
                        playsInline
                        preload="auto"
                        onPlaying={() => setIsVideoPlaying(true)}
                        onTimeUpdate={(e) => {
                            const vid = e.target as HTMLVideoElement;
                            if (vid.duration && vid.duration - vid.currentTime < 0.5) {
                                setIsFadingOut(true);
                            }
                        }}
                        onEnded={() => setIsVideoFinished(true)}
                        className={`w-full h-full object-cover md:object-contain relative z-10 transition-opacity duration-500 ease-in-out ${isVideoPlaying && !isFadingOut ? 'opacity-100' : 'opacity-0'}`}
                    />
                    {/* Fallback loader in case video finishes but images are still loading */}
                    {isVideoFinished && !isImagesLoaded && (
                        <div className="absolute bottom-10 flex flex-col items-center text-pink-500 font-mono tracking-widest font-bold z-10">
                            <div className="text-sm mb-2 animate-pulse">LOADING MAP...</div>
                            <div className="w-48 h-1 bg-slate-800 rounded-full overflow-hidden shadow-[0_0_15px_rgba(236,72,153,0.3)]">
                                <div
                                    className="h-full bg-pink-500 transition-all duration-200"
                                    style={{ width: `${(imagesLoaded / totalFrames) * 100}%` }}
                                />
                            </div>
                        </div>
                    )}
                </div>,
                document.body
            )}
            <canvas
                ref={canvasRef}
                className="fixed top-0 left-0 w-full h-full pointer-events-none z-0"
            />
        </>
    );
}
